services:
  mysql:
    image: mysql:8.0
    container_name: chat_service_mysql
    environment:
      MYSQL_DATABASE: chat_service_db
      MYSQL_USER: chat_service_user
      MYSQL_PASSWORD: chat_service_password
      MYSQL_ROOT_PASSWORD: chat_service_root_password
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    volumes:
      - chat_service_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    networks:
      - chat_service_network

  app:
    build: .
    container_name: chat_service_app
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://chat_service_user:chat_service_password@mysql:3306/chat_service_db?serverVersion=8.0"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chat_service_network

  nginx:
    image: nginx:alpine
    container_name: chat_service_nginx
    ports:
      - "8083:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - chat_service_network

volumes:
  chat_service_mysql_data:

networks:
  chat_service_network:
    driver: bridge
